<?php require 'templates/layout/header.phtml' ?>

<ul class="list-group">
<?php foreach($authors as $author): ?>
    <li class="list-group-item item-task">
        <div class="label">
            <b><?= htmlspecialchars($author->Nombre) ?></b>
        </div>
        <div class="actions">
            <a href="obras/<?= $author->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Libros</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> autores</small></p>


<?php require 'templates/layout/footer.phtml' ?>
