<?php require 'templates/layout/header.phtml' ?>
<?php if($this->user):?>
    <a href="cargarAutor" type="button" class='btn btn-primary btn-sm ml-auto mb-2'>Agregar Autor</a>
<?php endif;?>
<ul class="list-group">
<?php foreach($authors as $author): ?>
    <li class="list-group-item item-task">
        <div class="label">
            <b><?= htmlspecialchars($author->Nombre) ?> | <?= htmlspecialchars($author->GeneroDestacado) ?> | Premiaciones: <?= htmlspecialchars($author->Premiaciones) ?></b>
        </div>
        <div class="actions">
            <a href="obras/<?= $author->id ?>" type="button" class='btn btn-success btn-sm ml-auto'>Libros</a>
            <?php if($this->user):?>
                <a href="editarAutor/<?= $author->id ?>" type="button" class='btn btn-warning btn-sm ml-auto'>Editar</a>
                <a href="eliminarAutor/<?= $author->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Eliminar</a>
            <?php endif;?>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> autores</small></p>


<?php require 'templates/layout/footer.phtml' ?>