<?php require 'templates/layout/header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

<form method='post' action='login'>
    <div class='form-group'>
        <label for='name' class='mt-2'>Nombre de Usuario</label>
        <input type='text' class='form-control' id='name' name='name' required>
    </div>
    <div class='form-group'>
        <label for='password' class='mt-2'>Contraeña</label>
        <input type='password' class='form-control' id='password' name='password' required>
    </div>
    <button type='submit' class='btn btn-primary mt-3'>Iniciar Sesion</button>
</form>

<?php require 'templates/layout/footer.phtml' ?>