<?php require 'templates/layout/header.phtml' ?>



<ul class="list-group">
    <?php foreach($books as $book): ?>
        <li class="list-group-item item-task">
            <div class="label">
                <b><?= htmlspecialchars($book->Titulo) ?></b> 
            </div>
            <div class="actions">
                <a href="detalle/<?= $book->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Ver Mas</a>
                <?php if($this->user):?>
                    <a href="detalle/<?= $book->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Eliminar</a>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> libros</small></p>


<?php require 'templates/layout/footer.phtml' ?>