<?php require 'templates/layout/header.phtml' ?>



<ul class="list-group">
    <?php foreach($books as $book): ?>
        <li class="list-group-item item-task">
            <div class="label">
                <b><?= htmlspecialchars($book->Titulo) ?></b> 
            </div>
        </li>
    <?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> tareas</small></p>


<?php require 'templates/layout/footer.phtml' ?>