<?php require 'templates/layout/header.phtml' ?>

<h1><?= htmlspecialchars($data->Titulo) ?></h1>

<p>Genero: <?= htmlspecialchars($data->Genero) ?></p>

<p>Editorial: <?= htmlspecialchars($data->Editorial) ?></p>

<p>Cantidad de Paginas: <?= htmlspecialchars($data->CantidadPaginas) ?></p>

<p>Sinopsis: <?= htmlspecialchars($data->CantidadPaginas) ?></p> 


<?php require 'templates/layout/footer.phtml' ?>