<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>La Bóveda Literaria</title>
</head>

<body>
    <!-- main header -->
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <?php if($this->user):?>
                    <span class="navbar-text ms-3 me-3 text-primary fst-italic"><?= $this->user->name ?></span>
                <?php endif;?>
                <a class="navbar-brand" href="">La Bóveda Literaria</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="listarAutores">Autores</a>
                        </li>
                        <?php if($this->user):?>
                            <li class="nav-item">
                                <a class="nav-link text-danger" aria-current="page" href="logout">Cerrar Sesion</a>
                            </li>
                        <?php else:?>
                            <li class="nav-item">
                                <a class="nav-link text-success" aria-current="page" href="login">Iniciar Sesion</a>
                            </li>
                        <?php endif;?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="container mt-3">