<?php require 'layout/header.phtml' ?>
<form action="actualizarAutor/<?= $author->id ?>" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <h1><?= htmlspecialchars($author->Nombre) ?></h1>
                <p>Genero: <?= htmlspecialchars($author->GeneroDestacado) ?></p>
                <p>Premiaciones: <?= htmlspecialchars($author->Premiaciones) ?></p>
                <p>Fecha de Nacimiento: <?= htmlspecialchars($author->FechaNacimiento) ?></p>    
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Nuevo Genero Destacado</label>
                <input required name="gender" type="text" class="form-control">
                <label>Nuevas Premiaciones</label>
                <select required name="awards" class="form-control">
                    <option value="0">0</option>   
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                </select>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>
<?php require 'layout/footer.phtml' ?>